// mgeHost64 — W23: TILING CAUSTICS, generated by BEAM SPLATTING (differential photon mapping).
//
// WHY A SCATTER AND NOT A FORWARD MAP. The physical object is the Jacobian of the refraction map: a
// patch of surface of area dA focuses the light crossing it onto a patch of seabed of area
// |det J| dA, so the irradiance gain is 1/|det J|. Evaluated forward, per output texel, that has two
// problems and the second is fatal. It needs clamping, because |det J| passes through zero at a
// CAUSTIC — the singularity IS the effect, so the term that draws it is also the term that blows up.
// And past a fold the map stops being invertible: three surface points send light to the same seabed
// point, and a forward evaluation can only ever see one of them. The multi-sheet region is not a
// detail — the bright filament everyone recognises as a caustic is exactly the pile-up of those
// three pre-images. Scattering gets both for free: three pre-images landing in one texel are three
// atomic adds, and nothing is ever inverted.
//
// ⚠⚠ WHY THE SPLAT IS A GAUSSIAN AND NOT A POINT, which is the whole difference between this and the
// first version of this file. A photon does not carry a position, it carries a BEAM: the image of
// its own source cell under the refraction map. Deposited as a bilinear dot, that beam is a dot no
// matter how much the map stretched it, so wherever the map is expanding — which is to say deeper
// water — the deposits stop overlapping and the map fills with holes. That reads as NOISE, and it is
// not Poisson noise: more photons close the gaps only as sqrt(N), and no temporal EMA can help
// because the missing quantity is the beam's FOOTPRINT, not its sample count. Deposit each beam as a
// Gaussian the size of its own footprint and the gaps close at N unchanged.
//
// ⚠ AND THE FOOTPRINT MUST BE AN ELLIPSE, NOT A DISC. At a fold the beam collapses in ONE direction
// only, and that collapse IS the filament — an isotropic splat would blob away the exact feature
// being drawn. Concentrated beams therefore land as small bright ellipses and diverging beams as
// large dim ones, which is also what makes the depth behaviour come out right for free: deep slices
// are soft because their beams are genuinely wide, not because anything was blurred.
//
// ⚠ AND HERE THE JACOBIAN IS ANALYTIC, which is what makes this cheaper than the image-space
// caustic-mapping this technique comes from. Those methods finite-difference J out of a photon
// buffer. Ours is a closed form:
//
//     dst = x + c*D*grad(h)    =>    J = I + c*D*H(h)         H = the HESSIAN of h
//
// and h is a sum of cosines, so H is the same sincos the gradient already needs. J is symmetric
// (a Hessian is), so the footprint covariance is sigma_src^2 * J^2 with no transpose to form.
//
// ⚠ AND IT IS WHAT MAKES THIS SAFE TO PUT INSIDE THE EXPOSURE LOOP. Every beam deposits its full
// weight — the kernel is normalised by the SUM OF THE WEIGHTS IT ACTUALLY EVALUATED, not by the
// analytic Gaussian integral, so truncating the kernel misplaces energy but never loses it. N in,
// N out: the mean of the map is 1.0 BY CONSTRUCTION, not by tuning, so caustics redistribute the sun
// on the seabed without adding or removing any. A term that changed the mean would move the APL
// water/land split and the servo would chase it ([[project_forge_apl_region_split]],
// [[project_forge_exposure_couples_every_level]]). `w/l` is the number that reports it.
//
// ⚠ THE SOURCE GRID IS HEXAGONAL, AND THE ASPECT IS THE WHOLE POINT. A hex lattice is the optimal 2D
// covering: its worst-case gap to the nearest source is s/sqrt(3) = 0.577s against a square grid's
// s/sqrt(2) = 0.707s, so the same ray count leaves ~18% smaller holes for the ellipses to fill. But
// that only holds for a TRUE hex lattice. Offsetting alternate rows by half a cell while leaving the
// row spacing at 1 gives a brick lattice whose covering radius works out to exactly 0.707s — the
// square grid's number, i.e. no gain whatsoever for the trouble. The rows must ALSO be compressed to
// sqrt(3)/2, which is why the source grid is CAUSTIC_SRC_X x CAUSTIC_SRC_Y (256 x 296) and not
// square, and why it is decoupled from the RES x RES destination.
//
// ⚠ THE MAP TILES, AND THAT IS NOT NEGOTIABLE HERE — the same integer-lattice condition that makes
// the field seamless makes it repeat exactly every `tileWorldUnits`. What fights the repeat is the
// wave count above (featureless content tiles far less visibly than structured content) and, mostly,
// the DYNAMIC layer: ripples and wakes splatted into a second camera-anchored map that has no period
// at all. A consumer-side domain warp was tried and removed — hiding a repeat by shearing the lookup
// trades a periodic artefact for a smeared one, and the smear reads worse than the repeat did.
//
// TILING IS A LATTICE CONDITION, not a wrap mode. The height field is a sum of cosines whose
// wavevectors are INTEGER multiples of 2*pi/tile, so h is exactly periodic over the tile and so are
// its gradient and its Hessian; a beam leaving one edge is identical to one entering the other, and
// `dst mod S` is therefore not an approximation. Any non-integer wavevector would put a seam in the
// map that no amount of filtering removes. The source lattice tiles too, which needs CAUSTIC_SRC_Y
// EVEN so the half-row offset is periodic.
//
// DEPTH SLICES, because the depth evolution is the recognisable part: shallow water gives a sharp
// fine mesh, deep water a broad soft one, and the transition is what reads as "this is water" rather
// than "this is a texture of caustics". Four slices, lerped by the consumer in LOG depth.
//
// ⚠ THE MAP IS SINGLE-CHANNEL, AND THE DISPERSION FRINGE STILL WORKS. n(lambda) enters the
// displacement ONLY through c = 1 - 1/n, which multiplies D and nothing else — so a different
// wavelength is EXACTLY the same pattern at a slightly different depth. The consumer therefore gets
// its fringe by reading red and blue at a small offset along the DEPTH axis it is already
// interpolating, which costs nothing, needs no extra taps, and makes the fringe a runtime knob
// instead of something baked into three scattered channels. Storing three channels here would also
// have been storing almost nothing: the physical spread is 1.8%, which at these tile sizes is under
// half a texel of separation.
//
// ⚠ THE ANIMATION MUST BE PERIODIC AT THE TIME WRAP, AND IT IS NOT FOR FREE. The host wraps time at
// a fixed period so a float32 second does not quantise the motion. Wrapping is only invisible if the
// field returns to the same state, i.e. if every omega is a whole number of cycles over that period.
// omega = sqrt(g*K) is irrational and has no reason to be, so the un-snapped version teleported the
// entire map to a new phase every wrap — a jump on a fixed ~20 s beat.
//
// Fixed by SNAPPING each omega to a multiple of misc.y = 2*pi/period. The largest rounding is half a
// step, which against these omegas (10-18 rad/s at a 20 s wrap) is 0.9-1.6% — far inside what the
// dispersion relation is worth, and the ordering of the components is untouched, so long waves still
// crawl and short ones still scurry. ⚠ THE ANIMATION-RATE KNOB MUST BE SNAPPED WITH IT, not applied
// to time afterwards: scaling t by a non-integer rate re-breaks the periodicity exactly as before.
//
// ⚠ THE SUN'S ELEVATION ENTERS AT THE CONSUMER, NOT HERE, and only to FIRST order: the whole pattern
// translates by depth*tan(theta_water) along the sun's horizontal bearing, which is free. The
// pattern's SHEAR with elevation is second order and is deliberately not modelled — a low sun's
// caustics are slightly stretched along the bearing and this does not stretch them. Said out loud so
// the next reader knows it is a decision and not an oversight.
//
// Resource names are unique across all merged compute SRTs (house rule since the d3d.py aliasing
// bug), and there is exactly ONE SRT per header ([[project_forge_srt_one_per_header]]).
#pragma once

// Texels per side of one tile, and the number of depth slices — from the shared header, because the
// CONSUMER needs them too and must not include this file (it declares an SRT).
#include "caustic.h.fsl"

// The HEXAGONAL source lattice. X is free; Y must be X * 2/sqrt(3) = 1.1547 X for the cells to be
// equilateral, and must be EVEN (so the half-row offset tiles) and a multiple of the thread group.
// 512 * 1.1547 = 591.2 -> 592 = 74*8, a 0.13% aspect error that is not worth a fractional lattice.
#ifndef CAUSTIC_SRC_X
#define CAUSTIC_SRC_X 512
#endif
#ifndef CAUSTIC_SRC_Y
#define CAUSTIC_SRC_Y 592
#endif

// Cosine components in the tiling height field. ⚠ EIGHT WAS NOT ENOUGH, and the symptom was read as
// tiling: with only eight the sum is a recognisable INTERFERENCE FIGURE, and the eye latches onto
// that figure and matches it across tile boundaries. Twenty makes the tile's contents featureless,
// and featureless content tiles far less visibly than structured content does — which is a much
// cheaper lever than growing the tile, because the cost here is ALU inside a loop whose cost is
// dominated by the beam kernel's atomics, not by the sincos.
#ifndef CAUSTIC_WAVES
#define CAUSTIC_WAVES 20
#endif

// Beam weight is accumulated as FIXED POINT in a uint, because that is what atomics offer. Each beam
// deposits CAUSTIC_WFIX * (RES^2 / (SRC_X*SRC_Y)) spread over its ellipse, so the per-texel MEAN is
// exactly CAUSTIC_WFIX. It is 4096 rather than the 256 a point splat needed because a Gaussian's
// outer cells carry small FRACTIONS of the beam and quantising those to zero would both lose the
// ellipse's skirt and bias the mean. Headroom check: a 100x fold reaches 4.1e5, four orders inside
// uint32, and the pathological case of every beam landing in one texel is 2.7e8.
#ifndef CAUSTIC_WFIX
#define CAUSTIC_WFIX 4096u
#endif

STRUCT(CausticParams)
{
    // x = time, seconds, HOST-WRAPPED at a fixed period (like the water field's, and to the same
    //     period so the two cannot beat). The wrap is not optional: seconds-since-boot reaches ~1e6
    //     after a few days' uptime, where a float32 ULP is 60 ms, and 60 ms against an omega of 15
    //     rad/s is a 0.9 radian step. But see misc.y — a wrap is only invisible if the field is
    //     actually PERIODIC at that period, and this one is not periodic for free.
    // y = tile size in WORLD UNITS
    // z = sub-beams per source cell, per axis (1 = one beam per hex cell; 2 = 2x2 stratified, for
    //     when a single beam's LINEAR footprint is too crude across a hard fold)
    // w = temporal EMA weight for the new frame (1 = none; the field is deterministic, so this is
    //     for hiding residual stepping, not for hiding noise)
    DATA(float4, cfg,    None);
    // Per-slice depth in world units. The FIRST FOUR; W26's fifth static slice lives in depths2 at
    // the end of this struct, because a float4 holds four floats and this one is full.
    DATA(float4, depths, None);
    // x = c = 1 - 1/n at the reference wavelength (green). The ONLY place n enters the generator;
    //     red and blue are recovered by the consumer as a depth-axis offset (see the note above).
    // y = RMS surface slope. THE look knob: it sets how deep the first fold lands, because the
    //     focusing depth is 1/(c * slope * K). Too small and nothing focuses inside the depth
    //     ladder; too large and every slice is many folds past focus, which is chaos, not caustics.
    // z = tan of the sun's angular RADIUS in water (0.53 deg / 2 / n). Softens every beam by the
    //     sun's own size, which grows with depth and is why real deep caustics are soft.
    // w = animation rate multiplier (1 = the physical deep-water dispersion, omega = sqrt(g*K)).
    DATA(float4, wave,   None);
    // x = the round-robin CURSOR within this dispatch's slice group; the shader adds its own z and
    //     wraps modulo w. The static slices are round-robined across frames rather than all rebuilt
    //     every frame: at 512 the map costs four times what it did at 256, and a slice that is one
    //     frame stale is displaced by ~1 texel (the fastest wave component travels ~68 units/s),
    //     which is not a thing anyone can see. It is what pays for the resolution. The DYNAMIC
    //     dispatches rebuild every slice every frame, so their cursor is 0.
    // y = the WRAP FREQUENCY, 2*pi / (the period cfg.x is wrapped at). Every wave's omega is snapped
    //     to a whole multiple of this, which is what makes the wrap SEAMLESS — see the note below.
    // z = W24: the value the RESOLVE leaves in the accumulator on its way out. 0 for the static
    //     slices; CAUSTIC_WFIX for the dynamic ones, which is the IDENTITY PREFILL — see the note
    //     at the top of causticdyn.comp.fsl. This is the single number that makes a calm dynamic
    //     map cost zero atomics instead of one full splat per source cell.
    // w = the slice group's SPAN: the modulus the cursor wraps at, and the number of slices a
    //     resolve dispatch covers. 4 for the static group, 2 for ripple, 1 for wake, 3 for the
    //     dynamic resolve.
    DATA(float4, misc,   None);
    // ─── W24: THE DYNAMIC LAYERS ────────────────────────────────────────────────────────────────
    // All three appended at the END. Every lane above is written by a host expression that names it
    // positionally, and four descriptor-set instances now share this layout, so an insertion
    // anywhere else would silently re-point one dispatch's parameters at another's.
    //
    // THE SOURCE GRID IS THE FIELD ITSELF, WALKED AT AN INTEGER STRIDE. That is what makes the
    // dynamic taps exact integer loads rather than four-tap bilinear: destination texel (i,j) is
    // born at wave-field texel (i*stride + offset), so the caustic map's texel lattice IS a
    // sub-lattice of the wave field's. It also makes the domain follow the field's own texel-snapped
    // scroll for free — the map is rebuilt from scratch every frame, so there is no history to
    // resample and no parity to track.
    //   x = the field's world units per texel        (ripple 1, wake 8 — or 2.5 in MGE mode)
    //   y = the integer STRIDE in field texels       (ripple 1, wake 2)
    //   zw = the integer OFFSET in field texels of destination texel (0,0)
    DATA(float4, dynField, None);
    // x = the FIRST slice this dispatch writes (CAUSTIC_RIPPLE_BASE / CAUSTIC_WAKE_SLICE). Read by
    //     the resolve too, which is why it is not folded into misc.x.
    // y = the SLOPE GAIN applied to the field's stored .zw, and it must be the SAME number
    //     water.frag uses for that grid (g_ripSimSlope / g_wakeSlope). The caustic has to be cast
    //     by the surface you can see; a separate gain here would put the filaments under a
    //     disturbance of a different steepness than the normal map shows.
    // z = the field's grid size in texels, for clamping the +-1 taps at the border.
    // w = spare.
    DATA(float4, dynOut,   None);
    // x = the CALM threshold on displacement, in destination texels.
    // y = the CALM threshold on q*|H|, dimensionless.
    //     A beam under BOTH is returned immediately and contributes exactly the prefill it was
    //     already given. Only its kernel SHAPE is approximated (as a delta), and only in a ~1 texel
    //     band at the calm/disturbed boundary — where the disturbed kernel is a near-delta anyway.
    //     The BOOKKEEPING stays exact either way, which is what keeps the mean at 1.0.
    // zw = spare.
    DATA(float4, dynCfg,   None);
    // ─── W26: SLICE DEPTHS 4..7 ─────────────────────────────────────────────────────────────────
    // The static ladder grew to five entries and `depths` above holds four. APPENDED AT THE END for
    // the reason the W24 block a few lines up states in full — every lane in this struct is written
    // by a host expression that names it POSITIONALLY (cp[0]..cp[27]) and four descriptor-set
    // instances share the layout, so an insertion anywhere else silently re-points one dispatch's
    // parameters at another's. Putting the tail here also leaves room out to eight slices without a
    // second layout change.
    //
    // ⚠ ONLY caustic.comp READS IT: `li < 4 ? depths[li] : depths2[li - 4]`. causticdyn.comp walks
    // depths[0..span-1] with span <= 2 and causticresolve.comp reads no depth at all, so neither
    // changes — but fillDyn must still ZERO these lanes, because a persistently-mapped cbuffer keeps
    // whatever was last written to it.
    DATA(float4, depths2,  None);
    // ─── W26b: THE MEDIUM, AS A LOW-PASS ON THE SURFACE THIS SLICE IS CAST BY ───────────────────
    // x = k in sigma_scat = k * depth^1.5, world units — the small-angle multiple-scattering width
    //     of a pencil beam after `depth` of water, derived host-side from the water's OWN sigma_s.
    //     yzw spare.
    //
    // ⚠ IT DAMPS THE SURFACE SPECTRUM, IT DOES NOT BLUR THE MAP, and the two are the same physics
    // at the only place it is affordable. A beam that has spread to width sigma no longer samples a
    // point of the surface, it samples an AVERAGE over sigma — and averaging a sinusoid of
    // wavenumber K against a Gaussian of width sigma multiplies it by exp(-K^2*sigma^2/2), which is
    // just that Gaussian's transform. So the per-component damp below IS the beam spread, applied
    // where it costs one exp instead of a 44-texel convolution the splat kernel cannot reach
    // (CAUSTIC_KERNEL_CAP is 6; that attempt cost 5x and delivered a 13-texel box).
    //
    // ⚠ EXACT PRE-FOLD, AND BETTER THAN EXACT PAST IT. While the map is x + c*D*grad(h) with a small
    // displacement, structure scale is preserved, so damping the input and blurring the output are
    // the same operation. Past folding they diverge — and there the source taper is the RIGHT one,
    // because the fine components past their own fold depth contribute chaos, and this removes the
    // chaos rather than smearing it afterwards.
    //
    // MEASURED, on the real 20-component field (pattern half-life at best lag; contrast with the
    // model's lattice floor removed):
    //     depth 200:  75 ms -> >900 ms,  contrast 0.69 -> 0.89
    //     depth 300:  48 ms -> >900 ms,  contrast 0.50 -> 1.02
    //     depth 500:  29 ms -> >900 ms,  contrast 0.35 -> 0.59
    //     depth 800:  18 ms ->      --,  contrast 0.30 -> 0.00  (nothing survives, correctly)
    // Calmer AND more legible, which is why it answers "animates too fast" and "loses its shape"
    // with one term: what was there before was overlapping folded speckle from components whose
    // caustics the water had already destroyed.
    DATA(float4, medium,   None);
};

BEGIN_SRT(CausticSrtData)
    BEGIN_SRT_SET(Persistent)
        DECL_CBUFFER  (Persistent, CBUFFER(CausticParams), gCausticParams)
        // Beam counter, fixed point. ONE plane now that the map is single-channel:
        //   index = (slice*RES + y)*RES + x
        DECL_RWBUFFER (Persistent, RWBuffer(uint), gCausticAccum)
        // The finished map, one array slice per depth, single channel. Stored as (gain - 1) so that
        // ZERO IS THE IDENTITY — see the consumer note in opaque.srt.h. RW rather than W because the
        // optional temporal EMA reads its own texel back; that is safe in place precisely because no
        // thread reads a texel other than its own.
        DECL_RWTEXTURE(Persistent, RWTex2DArray(float), gCausticOut)
        // W24: the LIVE WAVE FIELD this dispatch splats — .x height .y velocity .zw slope per texel,
        // exactly the layout water.frag reads (ripplesim.srt.h).
        //
        // ⚠ ONE SLOT, NOT TWO, AND THE CHOICE OF FIELD IS A DESCRIPTOR-SET INSTANCE. Ripple and wake
        // already need separate cbuffer instances (they splat different domains into different
        // slices, and one mapped cbuffer shared between two RECORDED dispatches is read by both —
        // the RippleGrid::cbv[2] lesson), so the set instance is already the thing that says "which
        // dispatch is this". Hanging the texture off the same instance costs nothing and means
        // causticdyn.comp needs no runtime branch to pick a resource: ripple vs wake is entirely
        // cbuffer, which is what lets one shader serve both.
        //
        // Bound STATICALLY at creation. createRippleSimResources runs before createCausticResources,
        // and advanceRippleGrid/parkRippleGrid both leave tex[0] in SHADER_RESOURCE before this
        // block records — one of them runs unconditionally every frame — so there is no state to
        // track and no frame on which this can be read as a UAV.
        DECL_TEXTURE  (Persistent, Tex2D(float4), gCausticDynField)
    END_SRT_SET(Persistent)
END_SRT(CausticSrtData)
